In [15]:
import datetime as dt
import numpy as np

In [16]:
x=dt.date.today()
x.month


7

In [17]:
x=  dt.date(1997,2,20) +  dt.timedelta(10000)
print(x)


2024-07-08


In [18]:
y=dict(x='q',y='w')

In [19]:
y.append('c'='d')

SyntaxError: keyword can't be an expression (<ipython-input-19-3c5040274809>, line 1)

In [20]:
def tri(q,w):
    q=1/2*q*w
    print(q)

In [21]:
tri(2,3)

3.0


In [22]:
import numpy as np

In [23]:
a=np.array([[[2,3],[1,5],[2,3]],[[2,3],[1,5],[2,3]]])
print(a)
print("dimesi:",a.ndim)
print("type:",a.dtype)
print("size:",a.size)
print(a.shape)

[[[2 3]
  [1 5]
  [2 3]]

 [[2 3]
  [1 5]
  [2 3]]]
dimesi: 3
type: int32
size: 12
(2, 3, 2)


In [24]:
np.arange(6).reshape(1,1,1,1,1,6)

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

# Horizontal Split

In [25]:
a=np.arange(9).reshape(3,3)
b=np.arange(20,29).reshape(3,3)

In [26]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
b

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [28]:
np.hstack((a,b))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])

In [29]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [30]:
c=a+b

In [31]:
c


array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [32]:
float(c)

TypeError: only size-1 arrays can be converted to Python scalars

In [33]:
np.array.float(c)

AttributeError: 'builtin_function_or_method' object has no attribute 'float'

In [34]:
z=np.array([1,2,3,4],dtype='float')

# Pandas _ Panel Data

In [35]:
import pandas as pd 
import numpy as np

In [36]:
series = Series((np.arange(5)).index=['1','2','3','4','5'])
series

SyntaxError: keyword can't be an expression (<ipython-input-36-841d1259afcf>, line 1)

# - DataFrame

In [38]:
df = pd.DataFrame(np.random.rand(36).reshape(6,6),columns = ['r1', 'r2','r3', 'r4','r5', 'r6'])

In [39]:
df=df*100

In [40]:
df=np.floor(df)

In [41]:
df

r1    r2    r3    r4    r5    r6
0  28.0  23.0   3.0  60.0  11.0  49.0
1  32.0  79.0  56.0  10.0  62.0  77.0
2  42.0  32.0  14.0  88.0  44.0  91.0
3  97.0  46.0  94.0   7.0  52.0  53.0
4  94.0  41.0  99.0  83.0  30.0  61.0
5  13.0  66.0   2.0  50.0  45.0  82.0

In [62]:
import os
#path=os.getcwd()
path ='B:\\Machine Learning Bijay Explore\\DataMites\\Data'
os.chdir(path)
os.getcwd()

'B:\\Machine Learning Bijay Explore\\DataMites\\Data'

In [63]:
cars = pd.read_csv('mtcars.csv')

In [64]:
cars.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0       Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1   Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2      Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3  Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4      Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

   carb  
0     4  
1     4  
2     1  
3     1  
4     1

In [65]:
cars.shape

(32, 12)

In [66]:
autocars= cars[(cars.mpg > 30.0) & (cars.am==1)]

In [67]:
autocars

car_model   mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  \
17        Fiat 128  32.4    4  78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4  75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4   
27    Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.90   1   1     5   

    carb  
17     1  
18     2  
19     1  
27     2

In [68]:
autocars= cars[(cars.mpg > 30.0)]

In [69]:
autocars

car_model   mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  \
17        Fiat 128  32.4    4  78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4  75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4   
27    Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.90   1   1     5   

    carb  
17     1  
18     2  
19     1  
27     2

In [ ]:
data= [['Alax',10],['Ram',15],['biju',19]]

df =pd.DataFrame(data,dtype=float)

In [ ]:
df.columns=[['Name','Age']]

In [ ]:
df

In [ ]:
pdata = {'Name':['Ram','Shyama','Radhe','Shyam'],'Age':[12,22,34,56],'Gender':['Male','Female','Female','Male'],'working':['y','y','n','n']}

In [ ]:
df =pd.DataFrame(pdata)

In [ ]:
df

In [ ]:
df.Name[0]="Andy"

In [ ]:
df.loc[3,['Name','Gender']]=["Tasha","Female"]

In [14]:
np.nan ==" "
np

NameError: name 'np' is not defined

In [ ]:
df = pd.DataFrame(np.random.rand(20).reshape(5,4)) * 100
df

In [ ]:
df.to_csv('Class9.csv')